name: 'DIFF Action'

description: 'Github Action to compare files using diff'

inputs:
    first_file_path:
        description: 'repo/path/file.txt'
        required: true
    second_file_path:
        description: 'repo/path/file.txt'
        required: true
    expected_result:
        description: 'passed or failed'
        required: false
        default: 'passed'

outputs:
  diff-output:
    description: "Diff output"
    value: ${{ steps.diff.outputs.diff }}

# runs:
#     using: 'docker'
#     image: 'Dockerfile'
#     args:
#         - ${{ inputs.first_file_path }}
#         - ${{ inputs.second_file_path }}

runs:
  using: "composite"
  steps:

    - id: diff
      run: |
        if diff ${{ inputs.first_file_path }} ${{ inputs.second_file_path }} >/dev/null; then
          result=$(echo "passed")
        else
          result=$(echo "failed")
        fi
        echo Diff command result is $result
        echo "::set-output name=diff::$(echo $result)"
      shell: bash

    - run: |
        echo Output value is ${{ steps.diff.outputs.diff }}
        echo Expected value is ${{ inputs.expected_result }}
        if [ ${{ steps.diff.outputs.diff }} != ${{ inputs.expected_result }} ]; then
          echo "Output value NOT equal to Expected value!"
          exit 1
        else
          echo "Output value is equal to Expected value!"
        fi
      shell: bash

branding:
    icon: 'terminal'
    color: 'blue'