name: 'DIFF Action'

description: 'Github Action to compare files using diff'

inputs:
    first_file_path:
        description: 'repo/path/file.txt'
        required: true
    second_file_path:
        description: 'repo/path/file.txt'
        required: true

outputs:
  random-number:
    description: "Diff output"
    value: ${{ steps.diff.outputs.diff }}

# runs:
#     using: 'docker'
#     image: 'Dockerfile'
#     args:
#         - ${{ inputs.first_file_path }}
#         - ${{ inputs.second_file_path }}

runs:
  using: "composite"
  steps:

    - run: |
        echo First     
        if diff ${{ inputs.first_file_path }} ${{ inputs.second_file_path }} >/dev/null; then
          result=$(echo "Passed")
        else
          result=$(echo "Failed")
        fi
      shell: bash

    - id: diff
      run: |
        echo Second
        echo "::set-output name=diff::$(echo $result )"
      shell: bash

    - run: |
        echo Third
        echo "${{ steps.diff.outputs.diff }}"
      shell: bash

branding:
    icon: 'terminal'
    color: 'blue'