name: Diff Action Test (FILE Error)

on:
  push:
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls
      - uses: GuillaumeFalourd/diff-action@main
        with:
          first_file_path: file.txt
          second_file_path: file_nok.txt
          expected_result: PASSED

  macos:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls
      - uses: GuillaumeFalourd/diff-action@main
        with:
          first_file_path: file.txt
          second_file_path: file_nok.txt
          expected_result: PASSED

  windows:
    runs-on: windows-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls
      - uses: GuillaumeFalourd/diff-action@main
        with:
          first_file_path: file.txt
          second_file_path: file_nok.txt
          expected_result: PASSED
