name: Diff Action Test

on:
  workflow_dispatch:

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls
      - uses: GuillaumeFalourd/diff-action@main\
        with:
          first_file_path: file.txt
          second_file_path: file_ok.txt

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls
      - uses: GuillaumeFalourd/diff-action@main
        with:
          first_file_path: file.txt
          second_file_path: file_ok.txt

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: ls
      - uses: GuillaumeFalourd/diff-action@main
        with:
          first_file_path: file.txt
          second_file_path: file_ok.txt